#include <inttypes.h>
#include <time.h>

#include "board.h"
#include "attack.h"

/* --------------------------------------------------------------------------
 * MAGIC NUMBER GENERATION
 * -------------------------------------------------------------------------- */

// Generate a random 64-bit number with sparse bits
static uint64_t random_uint64_fewbits(void) {
    uint64_t u1 = (uint64_t)rand() & 0xFFFF;
    uint64_t u2 = (uint64_t)rand() & 0xFFFF;
    uint64_t u3 = (uint64_t)rand() & 0xFFFF;
    uint64_t u4 = (uint64_t)rand() & 0xFFFF;
    uint64_t r1 = u1 | (u2 << 16) | (u3 << 32) | (u4 << 48);
    
    u1 = (uint64_t)rand() & 0xFFFF;
    u2 = (uint64_t)rand() & 0xFFFF;
    u3 = (uint64_t)rand() & 0xFFFF;
    u4 = (uint64_t)rand() & 0xFFFF;
    uint64_t r2 = u1 | (u2 << 16) | (u3 << 32) | (u4 << 48);
    
    u1 = (uint64_t)rand() & 0xFFFF;
    u2 = (uint64_t)rand() & 0xFFFF;
    u3 = (uint64_t)rand() & 0xFFFF;
    u4 = (uint64_t)rand() & 0xFFFF;
    uint64_t r3 = u1 | (u2 << 16) | (u3 << 32) | (u4 << 48);
    
    return r1 & r2 & r3;
}

// Find a magic number for a given square
static uint64_t find_magic(int is_bishop, int sq) 
{
    bb_t occupancies[4096];
    bb_t attacks[4096];
    bb_t used[4096];
    // Get mask and generate all occupancy variations
    bb_t mask = is_bishop ? MASKS_BISHOP[sq] : MASKS_ROOK[sq];
    int bit_count = popcount(mask);
    int num_variations = 1 << bit_count;
    for (int i = 0; i < num_variations; i++) 
    {
        occupancies[i] = subset_from_index(i, bit_count, mask);
        attacks[i] = is_bishop 
            ? attacks_rook_slow(sq, occupancies[i])
            : attacks_bishop_slow(sq, occupancies[i]);
    }
    // Try random magic numbers
    for (int attempt = 0; attempt < 100000000; attempt++) 
    {
        uint64_t magic = random_uint64_fewbits();
        // Skip if not enough bits in upper byte
        if (popcount((mask * magic) & 0xFF00000000000000ULL) < 6)
            continue;
        // Test if this magic works
        for (int i = 0; i < 4096; i++)
            used[i] = 0ull;
        int fail = 0;
        for (int i = 0; !fail && i < num_variations; i++) {
            int index = transform(occupancies[i], magic, bit_count);
            if (used[index] == 0ull) {
                used[index] = attacks[i];
            } else if (used[index] != attacks[i]) {
                fail = 1;
            }
        }
        if (!fail)
            return magic;
    }
    return 0ULL;  // Failed to find magic
}

/* --------------------------------------------------------------------------
 * OUTPUT GENERATION
 * -------------------------------------------------------------------------- */

// Generate magic numbers for a piece type and write to file
static int generate_magics(FILE *fp, int is_bishop) 
{
    const char *piece_name = is_bishop ? "BISHOP" : "ROOK";
    fprintf(fp, "const uint64_t %s_MAGIC[64] = {\n", piece_name);
    for (int square = 0; square < 64; square++) {
        printf("\rComputing %s magic numbers: [%2d/64]", piece_name, square + 1);
        fflush(stdout);
        uint64_t magic = 0ULL;
        int attempts = 0;
        while (!magic && attempts < 5) {
            magic = find_magic(is_bishop, square);
            attempts++;
        }
        if (!magic) {
            fprintf(stderr, "\nFailed to find %s magic for square %d after %d attempts\n",
                    piece_name, square, attempts);
            return 1;
        }
        fprintf(fp, "    0x%016" PRIx64 "ull%s\n", magic, square < 63 ? "," : "");
    }
    fprintf(fp, "};\n\n");
    printf(" ✓\n");
    return 0;
}

// Write file header with warning and metadata
static void write_header(FILE *fp) 
{
    time_t now = time(NULL);
    char timestamp[64];
    strftime(timestamp, sizeof(timestamp), "%Y-%m-%d %H:%M:%S", localtime(&now));
    fprintf(fp, "/**\n");
    fprintf(fp, " * @file magic.c\n");
    fprintf(fp, " * @brief Magic bitboard lookup tables\n");
    fprintf(fp, " * \n");
    fprintf(fp, " * AUTO-GENERATED by gen_magics.c\n");
    fprintf(fp, " * \n");
    fprintf(fp, " * Generated: %s\n", timestamp);
    fprintf(fp, " */\n\n");
    fprintf(fp, "#include \"magic.h\"\n\n");
}

/* --------------------------------------------------------------------------
 * MAIN ENTRY POINT
 * -------------------------------------------------------------------------- */
int main(void) 
{
    srand((unsigned)time(NULL));
    _init_masks_rook();
    _init_masks_bishop();
    printf("Generating magic numbers\n");
    printf("======================\n\n");
    // Open output file
    FILE *fp = fopen("src/magic.c", "w");
    if (!fp) {
        fprintf(stderr, "Error: Cannot open magic.c for writing\n");
        return 1;
    }
    // Write header
    write_header(fp);
    // Generate rook magics
    if (generate_magics(fp, 0) != 0) {
        fclose(fp);
        return 1;
    }
    // Generate bishop magics
    if (generate_magics(fp, 1) != 0) {
        fclose(fp);
        return 1;
    }
    fclose(fp);
    printf("\nMagic numbers successfully generated in magic.c\n");
    printf("======================\n\n");
    return 0;
}
